version: '3'


services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./.dbdata/mysql/:/var/lib/mysql/
            - ./dbinit/mysql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
        network_mode: host
    localstack:
        image: localstack/localstack:latest
        volumes:
            - ./.localstack:/tmp/localstack
            - ./localstackinit/s3:/docker-entrypoint-initaws.d
        ports:
            - "4566:4566"
        environment:
            SERVICES: s3
            DEBUG: 1
            DATA_DIR: /tmp/localstack/data
            DEFAULT_REGION: us-west-2
        network_mode: host
